---
id: "b47d064b-255c-4bf6-a6e3-2ffa1de7f1a9"
illustration:
- "illustration_autumn_rain"
illustrationSquare: []
bpmInfo:
- start: 0.0
  bpm: 124.0
songId: "song_autumn_rain"
difficulty: "Cloudburst"
difficultyValue: 0.0
charter: "MUJI"
chartersRef:
- "people_muji"
chartId: "chart_b47d064b255c4bf6a6e32ffa1de7f1a9"
tags: []
