---
id: "347c9618-7ce2-4164-b683-99bade9a2ae7"
illustration:
- "illustration_autumn_rain"
illustrationSquare: []
bpmInfo:
- start: -0.05
  bpm: 124.0
songId: "song_autumn_rain"
difficulty: "Drizzle"
difficultyValue: 0.0
charter: "Icier"
chartersRef:
- "people_icier"
chartId: "chart_347c96187ce24164b68399bade9a2ae7"
tags: []
