---
id: "ab993c74-6067-4e6d-827f-b4de125f86f8"
illustration:
- "illustration_autumn_rain"
illustrationSquare: []
bpmInfo:
- start: -0.05
  bpm: 124.0
songId: "song_autumn_rain"
difficulty: "Sprinkle"
difficultyValue: 0.0
charter: "Icier"
chartersRef:
- "people_icier"
chartId: "chart_ab993c7460674e6d827fb4de125f86f8"
tags: []
