---
id: "7efee172-e8f7-4ffd-b63d-6646ade686ec"
illustration:
- "illustration_before_it_ends"
illustrationSquare: []
bpmInfo: []
songId: "song_before_it_ends"
difficulty: "Drizzle"
difficultyValue: 0.0
charter: "Magazet Never Ends"
chartersRef:
- "people_magazet"
chartId: "chart_7efee172e8f74ffdb63d6646ade686ec"
tags: []
