---
id: "195880a7-3550-4756-8d1d-97d064328775"
illustration:
- "illustration_before_it_ends"
illustrationSquare: []
bpmInfo: []
songId: "song_before_it_ends"
difficulty: "Cloudburst"
difficultyValue: 0.0
charter: "Ursulina Never Ends"
chartersRef:
- "people_magazet"
chartId: "chart_195880a7355047568d1d97d064328775"
tags: []
