---
id: "37f5c629-d6c5-4996-bd45-1a6903101111"
illustration:
- "illustration_before_it_ends"
illustrationSquare: []
bpmInfo: []
songId: "song_before_it_ends"
difficulty: "Sprinkle"
difficultyValue: 0.0
charter: "Magazet Never Ends"
chartersRef:
- "people_magazet"
chartId: "chart_37f5c629d6c54996bd451a6903101111"
tags: []
