---
id: "d714a7fe-53d5-43a1-afe3-8951d8b3aad9"
illustration: "illustration_broken_conviction"
bpmInfo:
  - start: 0.07
    bpm: 180.0
    beatsPerBar: 0
songId: "song_broken_conviction"
difficulty: "Drizzle"
difficultyValue: 0.0
charter: "Akko"
chartersRef:
  - "people_akko"
chartId: "chart_7c30226f0ea54b71aab77fefca1070dd"
tags: [ ]
