---
id: "57229919-1eda-45c9-bcfd-8b77d895fecb"
illustration:
- "illustration_conflict"
illustrationSquare: []
bpmInfo:
- start: -0.019
  bpm: 160.0
songId: "song_conflict"
difficulty: "Cloudburst"
difficultyValue: 0.0
charter: "tcstwtbhy + akko"
chartersRef:
- "people_tcstwtbhy"
- "people_akko"
chartId: "chart_conflict_cloudburst"
tags: []
