---
id: "a6ea8ba3-6258-4734-b906-af8da2f6d7b0"
illustration:
- "illustration_deluge"
illustrationSquare: []
bpmInfo:
- start: 0.1
  bpm: 132.0
songId: "song_deluge"
difficulty: "Drizzle"
difficultyValue: 0.0
charter: "Magazet vs. Ursulina"
chartersRef:
- "people_magazet"
chartId: "chart_a6ea8ba362584734b906af8da2f6d7b0"
tags: []
