---
id: "df81f1f6-eb27-470e-87bd-4f17508ffe62"
illustration:
- "illustration_ephemeric_world"
illustrationSquare: []
bpmInfo:
- start: 0.001
  bpm: 200.0
songId: "song_ephemeric_world"
difficulty: "Cloudburst"
difficultyValue: 0.0
charter: "Matrix///Blanchet"
chartersRef:
- "people_shuxuezhu"
chartId: "chart_ephemeric_world_cloudburst"
tags: []
