---
id: "a55f41e2-a610-4f4e-aa8f-daf8269987dc"
illustration:
- "illustration_ephemeric_world"
illustrationSquare: []
bpmInfo:
- start: 0.001
  bpm: 200.0
songId: "song_ephemeric_world"
difficulty: "Sprinkle"
difficultyValue: 0.0
charter: "Kiyotsuki"
chartersRef:
- "people_kiyotsuki"
chartId: "chart_ephemeric_world_sprinkle"
tags: []
