---
id: "bea32197-37da-47d8-b18f-ca8449bf3cf7"
illustration:
- "illustration_fantasia_sonata_hope"
illustrationSquare: []
bpmInfo:
- start: -0.01
  bpm: 231.0
songId: "song_fantasia_sonata_hope"
difficulty: "Drizzle"
difficultyValue: 0.0
charter: "Akko"
chartersRef:
- "people_akko"
chartId: "chart_bea3219737da47d8b18fca8449bf3cf7"
tags: []
