---
id: "27c295cf-2094-40ab-8647-beb65a257443"
illustration:
- "illustration_fantasia_sonata_hope"
illustrationSquare: []
bpmInfo:
- start: -0.01
  bpm: 231.0
songId: "song_fantasia_sonata_hope"
difficulty: "Sprinkle"
difficultyValue: 0.0
charter: "Akko"
chartersRef:
- "people_akko"
chartId: "chart_27c295cf209440ab8647beb65a257443"
tags: []
