---
id: "fb7b7388-ee38-488d-8d59-81397b6277d9"
illustration:
- "illustration_fantasia_sonata_hope"
illustrationSquare: []
bpmInfo:
- start: -0.01
  bpm: 231.0
songId: "song_fantasia_sonata_hope"
difficulty: "Cloudburst"
difficultyValue: 0.0
charter: "Akko"
chartersRef:
- "people_akko"
chartId: "chart_fb7b7388ee38488d8d5981397b6277d9"
tags: []
