---
id: "b3585c5d-6936-4129-b45c-edc40026e7ac"
illustration:
- "illustration_fluorescent_light"
illustrationSquare: []
bpmInfo:
- start: 1.722
  bpm: 138.0
- start: 45.183
  bpm: 213.0
songId: "song_fluorescent_light"
difficulty: "Sprinkle"
difficultyValue: 0.0
charter: "Akko"
chartersRef:
- "people_akko"
chartId: "chart_b3585c5d69364129b45cedc40026e7ac"
tags: []
