---
id: "cab72aa4-2891-4485-90b6-9fd803cecf60"
illustration:
- "illustration_fluorescent_light"
illustrationSquare: []
bpmInfo:
- start: 1.722
  bpm: 138.0
- start: 45.183
  bpm: 213.0
songId: "song_fluorescent_light"
difficulty: "Drizzle"
difficultyValue: 0.0
charter: "Akko"
chartersRef:
- "people_akko"
chartId: "chart_cab72aa42891448590b69fd803cecf60"
tags: []
