---
id: "f32e28cf-c2d3-4981-88e7-200eb2daab15"
illustration:
- "illustration_fluorescent_light"
illustrationSquare: []
bpmInfo:
- start: 1.722
  bpm: 138.0
- start: 45.183
  bpm: 213.0
songId: "song_fluorescent_light"
difficulty: "Cloudburst"
difficultyValue: 0.0
charter: "Akko"
chartersRef:
- "people_akko"
chartId: "chart_f32e28cfc2d3498188e7200eb2daab15"
tags: []
