---
id: "59af276a-3e2a-4c05-be72-2572cbdbae5c"
illustration:
- "illustration_life_garden"
illustrationSquare: []
bpmInfo:
- start: 1.706
  bpm: 149.0
songId: "song_life_garden_extended_mix"
difficulty: "Clear"
difficultyValue: 0.0
charter: "Milthm Team"
chartersRef:
- "people_milthm_team"
chartId: "chart_life_garden_extended_mix_clear"
tags: []
