---
id: "72d3d925-136e-48f9-a4d4-75a0c5460cb4"
illustration:
- "illustration_pthahnil"
illustrationSquare: []
bpmInfo:
- start: -0.16
  bpm: 160.0
songId: "song_pthahnil"
difficulty: "Cloudburst"
difficultyValue: 0.0
charter: "『Fallen Angel』Magazet - \"NM=Left EX=Right\""
chartersRef:
- "people_magazet"
chartId: "chart_72d3d925136e48f9a4d475a0c5460cb4"
tags: []
