---
id: "442a982d-fdea-45bb-a201-81df43a64543"
illustration:
- "illustration_pthahnil"
illustrationSquare: []
bpmInfo:
- start: -0.16
  bpm: 160.0
songId: "song_pthahnil"
difficulty: "Sprinkle"
difficultyValue: 0.0
charter: "『Fallen Angel』Magazet - \"NM=Left EX=Right\""
chartersRef:
- "people_magazet"
chartId: "chart_442a982dfdea45bba20181df43a64543"
tags: []
