---
id: "ef43ff97-deaf-4323-b354-70f52d9e5461"
illustration:
- "illustration_soneday_i_will_forget"
illustrationSquare: []
bpmInfo:
- start: 0.0
  bpm: 180.0
songId: "song_soneday_i_will_forget"
difficulty: "Cloudburst"
difficultyValue: 0.0
charter: "BlueDream0"
chartersRef:
- "people_magazet"
chartId: "chart_ef43ff97deaf4323b35470f52d9e5461"
tags: []
