---
id: "ae8b037d-36ec-49f0-aca2-983f01bfb6c7"
illustration:
- "illustration_soneday_i_will_forget"
illustrationSquare: []
bpmInfo:
- start: 0.0
  bpm: 180.0
songId: "song_soneday_i_will_forget"
difficulty: "Drizzle"
difficultyValue: 0.0
charter: "BlueDream0"
chartersRef:
- "people_magazet"
chartId: "chart_ae8b037d36ec49f0aca2983f01bfb6c7"
tags: []
