---
id: "50efadfb-ae2c-4e1f-aa1d-81cd90641db0"
illustration:
- "illustration_soneday_i_will_forget"
illustrationSquare: []
bpmInfo:
- start: 0.0
  bpm: 180.0
songId: "song_soneday_i_will_forget"
difficulty: "Sprinkle"
difficultyValue: 0.0
charter: "BlueDream0"
chartersRef:
- "people_magazet"
chartId: "chart_50efadfbae2c4e1faa1d81cd90641db0"
tags: []
