---
id: "5144879f-47c9-4c2c-a072-8189afe85771"
illustration:
- "illustration_unmei"
illustrationSquare: []
bpmInfo:
- start: 0.06
  bpm: 182.0
songId: "song_unmei"
difficulty: "Cloudburst"
difficultyValue: 0.0
charter: "Particle & xzadudu179"
chartersRef:
- "people_akko"
- "people_xzadudu179"
chartId: "chart_5144879f47c94c2ca0728189afe85771"
tags: []
