---
id: "e0cb3704-d30e-4f01-ac56-2be215269d7d"
illustration:
- "illustration_unmei"
illustrationSquare: []
bpmInfo:
- start: 0.06
  bpm: 182.0
songId: "song_unmei"
difficulty: "Sprinkle"
difficultyValue: 0.0
charter: "Particle of Crystal"
chartersRef:
  - "people_icier"
  - "people_akko"
chartId: "chart_e0cb3704d30e4f01ac562be215269d7d"
tags: []
