---
id: "d0d29240-8b57-4c50-905d-7a0350e05fca"
illustration:
- "illustration_unmei"
illustrationSquare: []
bpmInfo:
- start: 0.06
  bpm: 182.0
songId: "song_unmei"
difficulty: "Drizzle"
difficultyValue: 0.0
charter: "Crystal with Particle"
chartersRef:
- "people_icier"
- "people_akko"
chartId: "chart_d0d292408b574c50905d7a0350e05fca"
tags: []
